### PR TITLE
Devel

### PR DESCRIPTION
**Pull request by matteodefelice**
A function named ‘gridDataWrapper’ is proposed to let the user have the
possibility to ‘transform’ an array into a proper grid data to be used
with downscaleR and the other packages.

I tested the packages a while and it seems consistent but obviously it
should be checked further.

I had to include the lubridate package to deal with monthly time
intervals (I know it’s stupid, see here for more details
http://stackoverflow.com/questions/14169620/add-a-month-to-a-date/141823
26#14182326 )

### CODE REVIEW

**Comment by jbedia** [comment]
Hi Matteo, sorry for slow reaction on this. It seems a potentially useful addition to the package. I will test it and give you some feedback asap. Thanks!

**Comment by matteodefelice** [comment]
Hi Joaquin, I need to use the gridDataWrapper to import EC-EARTH data into the ecomsUDG ecosystem, what's the status on this pull request? Just to know, otherwise I'll use a forked repo, 
grazie

**Comment by jbedia** [comment]
Hi Matteo, sorry, I am back with this... We are preparing a new function for loading forecasts in loadeR, assuming a "standard" definition via NcML. My impression is that it is not worth including now this wrapper provided it is just a temporary solution, however, I do not want to impose my opinion here... What do you think? If you can use the wrapper this time go ahead with your fork. I will keep you informed on progresses with reading generic forecasts. Shall we meet in Bolzano? cheers

**Comment by matteodefelice** [comment]
Good news,! It depends on when you are going to release these new
functions, in a few weeks? Just to know, otherwise I will use my solution
waiting for an official one, what do you think?

Ps I'll be in Bolzano sure!
Il 03/mag/2016 10:05 AM, "Joaquin Bedia" <notifications@github.com> ha
scritto:

**Comment by jbedia** [comment]
It will be ready presto, a beta version will be ready before Bolzano for your testing
cheers

**Pull request closed without merging**
